# Recursion
## Presentation to Cambridge Python Group
## 1/8/2021

What is recursion?

A function or algorithm is recursive if it calls itself. For instance, consider the definition of a factorial:

$n! = \Pi_{i=1}^{n}n = n*(n-1)*(n-2)* \ldots *2*1 = n*((n-1)!)$, $0! = 1$

Here's an example of how we can implement this function in Python:



In [1]:
def factorial(n):
    # base case
    if n == 0:
        return 1
    # recursive case
    else:
        return n*factorial(n-1)

print("0! = ", factorial(0))
print("1! = ", factorial(1))
print("4! = ", factorial(4))
print("10! = ", factorial(10))

0! =  1
1! =  1
4! =  24
10! =  3628800


A lot of computer scientists like to name programming languages, operating systems, etc. using (infinite) recursion:

GNU: GNU's not UNIX

YAML: YAML Ain't Markdown Language




There's a whole [Wikipedia article](https://en.wikipedia.org/wiki/Recursive_acronym) devoted to these acronyms.

It wouldn't be an HS meeting without [Dilbert](https://dilbert.com/strip/1994-05-18)

We can also use recursion to perform more complex operations. Consider the following implementation of depth-first search using an arbitrary directory as the root node:

In [2]:
import os

# Depth-first search traverses a tree by visiting its root, then
# running depth-first search on each branch of the root. If the
# root has no subdirectories/branches, it returns without doing
# anything. Depth-first search can be useful for exploring a
# tree or graph of unknown size (in this case, a directory and
# its subdirectories)

# the dir argument should contain an absolute file path
# the depth argument just adds a given number of spaces before the
# name of a directory is printed

def dfs(dir, depth=0):
    
    # this just guarantees that the "root" folder gets printed
    if depth == 0:
        print(dir)
    try:
        subdirs = next(os.walk(dir))[1] # get a list of all subdirectories of dir
        
    # base case: if a directory has no subdirectories, don't do anything
    except StopIteration: # next(os.walk(dir)) triggers a StopIteration error if there are no subdirectories of dir
        return
    else:
        # recursive case: print the name of the directory, then run dfs on each subdirectory
        for subdir in subdirs:
            print(" "*depth, subdir)
            dfs(dir + "/" + subdir, depth+1)
    
dfs("c:/users/wleith/documents")

c:/users/wleith/documents
 My Music
 My Pictures
 My Videos
 NEU
  .git
   hooks
   info
   logs
    refs
     heads
     remotes
      origin
   objects
    01
    06
    08
    0c
    0d
    0e
    11
    1c
    1f
    28
    2c
    2d
    2f
    30
    31
    37
    3a
    41
    48
    4a
    4b
    4d
    4e
    4f
    50
    51
    53
    54
    55
    59
    5d
    5e
    62
    63
    69
    6a
    6b
    6d
    70
    71
    72
    75
    76
    7a
    7b
    7c
    7e
    83
    84
    8a
    8c
    8d
    8f
    91
    92
    94
    95
    9a
    9e
    9f
    a0
    a5
    a7
    aa
    ab
    ac
    b0
    b7
    b9
    ba
    bc
    bf
    c0
    c1
    c2
    c6
    c9
    ca
    cb
    ce
    cf
    d0
    d2
    d3
    d4
    d5
    d6
    d7
    da
    de
    e3
    e4
    e6
    e9
    f0
    f1
    f4
    fa
    fc
    info
    pack
   refs
    heads
    remotes
     origin
    tags
  Algorithms
  Linear Algebra and Probability
  Unsupervised Machine Learning
   .ip

  .git
   hooks
   info
   logs
    refs
     heads
     remotes
      origin
   objects
    01
    07
    09
    0a
    0b
    0c
    12
    14
    16
    18
    21
    27
    2e
    2f
    31
    37
    3c
    3e
    3f
    41
    45
    47
    49
    4c
    52
    5a
    5b
    5d
    5f
    60
    61
    62
    64
    68
    6d
    6e
    6f
    73
    7b
    7e
    83
    84
    85
    86
    8c
    91
    94
    95
    98
    9a
    9e
    9f
    a3
    a4
    aa
    b0
    b1
    b2
    b4
    b5
    b8
    bd
    be
    c0
    c9
    cc
    d2
    da
    db
    e5
    e6
    e7
    eb
    ef
    f3
    f4
    f8
    f9
    fc
    fe
    info
    pack
   refs
    heads
    remotes
     origin
    tags
  .ipynb_checkpoints
  MyFiles
   Bike Receipts
    2019
    2020
   Delayed Baggage Materials
    Leith Claim Materials
   Donations
    2019
    2020
   Dr. Fogel
    2019-2019
   Feedback
   Housing
   NEU
  Python Table Programs
   Filled Shells
   word_input_ex1
   word_input_

In some situations, recursion may not be an appropriate choice. For instance, consider the Fibonacci numbers. The formula for the $n$th Fibonacci number implies that it should be a good candidate for a recursive implementation:

$f_{n} = f_{n-1} + f_{n-2}$



In [3]:
def fibonacci(n):
    # base case 1: fibonacci(0) = 0
    if n == 0:
        print("Calculating fibonacci( 0 )...")
        return 0
    # base case 2: fibonacci(1) = 1
    elif n == 1:
        print("Calculating fibonacci( 1 )...")
        return 1
    # recursive case: fibonacci(n) = fibonacci(n-1) + fibonacci(n-2)
    else:
        print("Calculating fibonacci(",n,")...")
        return(fibonacci(n-1) + fibonacci(n-2))

However, this can quickly lead to an error due to redundant calculations, as illustrated by this (verbose) implementation of a recursive Fibonacci number function:

The function needs to be called 15 times to calculate $f_{5}$:

In [4]:
print(fibonacci(5))

Calculating fibonacci( 5 )...
Calculating fibonacci( 4 )...
Calculating fibonacci( 3 )...
Calculating fibonacci( 2 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 0 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 2 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 0 )...
Calculating fibonacci( 3 )...
Calculating fibonacci( 2 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 0 )...
Calculating fibonacci( 1 )...
5


But far more calls are required for $f_{10}$:

In [5]:
print(fibonacci(10))

Calculating fibonacci( 10 )...
Calculating fibonacci( 9 )...
Calculating fibonacci( 8 )...
Calculating fibonacci( 7 )...
Calculating fibonacci( 6 )...
Calculating fibonacci( 5 )...
Calculating fibonacci( 4 )...
Calculating fibonacci( 3 )...
Calculating fibonacci( 2 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 0 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 2 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 0 )...
Calculating fibonacci( 3 )...
Calculating fibonacci( 2 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 0 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 4 )...
Calculating fibonacci( 3 )...
Calculating fibonacci( 2 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 0 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 2 )...
Calculating fibonacci( 1 )...
Calculating fibonacci( 0 )...
Calculating fibonacci( 5 )...
Calculating fibonacci( 4 )...
Calculating fibonacci( 3 )...
Calculating fibonacci( 2 )...
Calculati

A (non-recursive) linear-time implementation (i.e. an implementation where the number of operations is a scalar multiple of the input size) of the fibonacci function would look something like this:

In [7]:
import numpy as np

def fibonacci_linear(n):
    
    # initialize an array of length 2 that is filled with 1s
    f = np.empty(2)
    f[0] = 0
    f[1] = 1
    
    # indices for looping over the array
    p, q = 0, 1
    
    # if we have already calculated the nth fibonacci number,
    # return it
    if n <= len(f):
        return int(f[n])
    else:
        # otherwise, fib(n) = fib(n-1) + fib(n-2)
        for i in range(0,n-1):
            f = np.append(f, [f[p] + f[q]])
            p += 1
            q += 1
        return int(f[n])

print("fibonacci(0) = ", fibonacci_linear(0))
print("fibonacci(1) = ", fibonacci_linear(1))
print("fibonacci(5) = ", fibonacci_linear(5))
print("fibonacci(10) =", fibonacci_linear(10))

        

fibonacci(0) =  0
fibonacci(1) =  1
fibonacci(5) =  5
fibonacci(10) = 55


Recursive functions can result in "Stack Overflow" errors because each call to the function is pushed onto a "stack" of commands to be executed (a stack is a "first in first out" data structure, where only the most recently inserted element may be accessed). Stack overflow errors occur when the "stack" of commands exceeds available memory.

In general, commands are pushed onto the stack and "popped" out one at a time, so stack overflow errors are typically a sign that something went wrong with a recursive function.

A couple of other notable recursive functions include mergesort...

In [9]:
# this method merges two sorted arrays by comparing
# the i-th elemet of a1 to the j-th element of a2
# and appending the smaller of the two elements onto
# the end of m, where the sorted array to be returned
# is stored. Then i or j is incremented (depending on
# which array had the smaller value) until all elements
# of each array have been considered. This method is
# NOT recursive, but it is called in the recursive
# merge_sort method below

def merge(a1, a2, verbose=False):
    i = 0
    j = 0
    m = []
    
    while True: # this is kind of lazy but it works since
                # we just want to iterate until we reach
                # the end of both arrays
                
        # case 1: we have reached the end of both arrays (do nothing)
        if i == len(a1) and j == len(a2):
            return(m)
        
        # case 2: we have reached the end of a1 but not a2
        elif i == len(a1) and j < len(a2):
            m.append(a2[j])
            j += 1
            
        # case 3: we have reached the end of a2 but not a1
        elif j == len(a2) and i < len(a1):
            m.append(a1[i])
            i += 1
            
        # case 4: we haven't reached the end of either array, and
        #         the ith entry of a1 is greater than the jth entry
        #         of a2
        elif a1[i] > a2[j]:
            m.append(a2[j])
            j += 1
            
        # case 5: we haven't reached the end of either array, and
        #         the ith entry of a1 is less than or equal to
        #         the jth entry of a1
        else:
            m.append(a1[i])
            i += 1
        if verbose:
            print(m)

        
# merge([1,2,3],[4,5,6], verbose = True)

def merge_sort(a, verbose = True):
    # base case: an array of length 0 or 1 is already sorted
    if len(a) <= 1:
        return a
    # recursive case: sort arrays of length >= 2 by splitting
    #                 them into 2 smaller arrays and merge()ing
    #                 the resulting (smaller) arrays
    else:
        pivot = int(len(a)/2)
        a1 = a[:pivot]
        a2 = a[pivot:]
        if verbose:
            print("merging", a1, "and", a2)
        # multiple recursive calls in a single line
        return merge(merge_sort(a1),merge_sort(a2), verbose = verbose)
    
a = merge_sort([1,3,4,2,6,5])

merging [1, 3, 4] and [2, 6, 5]
merging [1] and [3, 4]
merging [3] and [4]
[3]
[3, 4]
[1]
[1, 3]
[1, 3, 4]
merging [2] and [6, 5]
merging [6] and [5]
[5]
[5, 6]
[2]
[2, 5]
[2, 5, 6]
[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


...and binary search

In [11]:
# binary search determines whether an element is present in a sorted
# array in O(logN) time by partitioning an array on its median
# (the floor(N/2)th element) and keeping the array containing smaller
# values if the value being searched for (x) is less than floor(N/2)
# and keeping the array containing larger values otherwise.

def binary_search(a, x):
    # base case 1: an array of length 0
    if len(a) == 0:
        return False
    # base case 2: an array of length 1
    elif len(a) == 1:
        return a[0] == x
    # recursive case
    else:
        return binary_search(a[:int(len(a)/2)], x) or binary_search(a[int(len(a)/2):], x)
    
print(binary_search(a, 5))
print(binary_search(a, 7))

True
False


## Recursive backtracking:

Recursion can also be used to incrementally find a solution to a problem by eliminating invalid solutions when they are encountered. This can be applied to common algorithmic problems such as n-queens, maze-solving, and sudokus.

Backtracking algorithms can be summarized as follows:

1. given a problem, impose a constraint

2. try to solve the constrained instance of the problem (i.e. go back to step 1, but with the constrained problem)

3. if that constraint does not result in a solution but it is possible to impose a different constraint, impose that constraint instead and try to solve the constrained problem (i.e. go back to step 1, but with the constrained problem)

4. if all possible constraints have been tried, the problem has no solution



In [12]:
# example: the knight's tour
# given an N x N chessboard, visit each square with a knight exactly once

import numpy as np

def is_valid(board,x,y,N):
    # avoid index out of range exceptions
    if x < 0 or y < 0 or x >= N or y >= N:
        #print(x, y)
        return False
    else:
        # return true if space is unvisited
        return board[x][y] == -1
    
def knights_tour(board, x, y, move, N):
    
    # all the valid moves that a knight can make
    # i.e. one square to the right and two squares down
    #      one square to the right and two squares up
    #      one square to the left and two squares down
    #      one square to the left and two squares up
    #      two squares to the right and one square down
    #      two squares to the right and one square up
    #      two squares to the left and one square down
    #      two squares to the left and one square down
    moves_x = [1, 1,-1,-1, 2, 2,-2,-2]
    moves_y = [2,-2, 2,-2, 1,-1, 1,-1]
    
    # if N^2 moves have been completed with no repeats, a solution exists!
    if move == N**2:
        print("Solution exists")
        print()
        print(board)
        return True
    
    # if < N^2 moves have been completed, traverse over all the possible moves from
    # the current square
    for i in range(0,8):
        #print("move", move, ": trying", x + moves_x[i], ",", y + moves_y[i], "(" + str(i) + ")")
        
        # if a move is valid (i.e. if some reachable square has not yet been visited), attempt
        # to continue the tour from that square
        if is_valid(board, x + moves_x[i], y + moves_y[i], N):
            board[x + moves_x[i]][y + moves_y[i]] = move
            #print(board)
            
            # if it is possible to complete the tour from a given square, return true
            if knights_tour(board, x + moves_x[i], y + moves_y[i], move + 1, N):
                return True
            
            
            # backtrack (if a move does not lead to any completed tours)
            board[x + moves_x[i]][y + moves_y[i]] = -1
    
    # if no solution exists, return false
    # note that solve_kt(N) below will return false if no tour beginning
    # at (0,0) may be completed for an N x N board
    #print("No solution exists")
    return False
        
def solve_kt(N):
    board = np.empty(shape = (N,N))
    board.fill(-1)
    board[0][0] = 0
    return knights_tour(board,0,0,1,N)

solve_kt(6) # this is the smallest non-trivial instance of the problem with a solution


Solution exists

[[  0.  21.  12.  29.  32.  35.]
 [ 11.  28.   1.  34.  13.  30.]
 [ 20.   7.  22.  31.   2.  33.]
 [ 27.  10.   3.  16.  23.  14.]
 [  6.  19.   8.  25.   4.  17.]
 [  9.  26.   5.  18.  15.  24.]]


True

Recursive backtracking can be really useful when the size of a problem is small, but it is still an implementation of brute-force search. The algorithm above runs in factorial time, which is useless for large input sizes. For unconstrained problem sizes, it is usually worth looking for "greedy" or "dynamic programming" solutions. If you un-comment the print statements and run the code block above, you'll see that there are thousands of recursive calls for an instance with N=6.